from pathlib import Path
from typing import List
from langchain_community.document_loaders import TextLoader
from langchain_core.documents import Document

def load_cleaned_md_documents(md_dir: str) -> List[Document]:
    """
    Loads the Markdown files generated by Docling.
    """
    data_path = Path(md_dir).resolve()
    documents = []

    # Target only .md files
    md_files = list(data_path.glob('**/*.md'))
    print(f"[DEBUG] Found {len(md_files)} Markdown files.")

    for md_file in md_files:
        try:
            # We use TextLoader because the content is already clean Markdown text
            loader = TextLoader(str(md_file), encoding="utf-8")
            loaded_docs = loader.load()
            
            # Add metadata to help the AI know which part of the FD Advisory it's reading
            for doc in loaded_docs:
                doc.metadata["source_file"] = md_file.name
                documents.append(doc)
                
            print(f"[SUCCESS] Loaded: {md_file.name}")
        except Exception as e:
            print(f"[ERROR] Failed to load {md_file}: {e}")
            
    return documents